#!/usr/bin/env bash

if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file=$1
ip=$2
user=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i $ssh_key $file $user@$ip:~

